// Code generated by "stringer -type=TieProperty -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TieUid-0]
	_ = x[TieFilename-1]
	_ = x[TieFilesize-2]
	_ = x[TieName-3]
	_ = x[TieMediaType-4]
	_ = x[TieFileHost-5]
	_ = x[TieTag-6]
	_ = x[TiePath-7]
	_ = x[TieParent-8]
	_ = x[TieTags-9]
	_ = x[TieTagDate-10]
	_ = x[TieCollection-11]
	_ = x[TieTypeProperty-12]
	_ = x[TieAll-13]
	_ = x[TieTitle-14]
	_ = x[TieArtist-15]
	_ = x[TieAlbum-16]
	_ = x[TieYear-17]
	_ = x[TieTrack-18]
	_ = x[TieTiedirHash-19]
	_ = x[TieDirUID-20]
	_ = x[TieVersionOf-21]
	_ = x[TieVersionDate-22]
}

const _TieProperty_name = "tie-uidfilenamefilesizenamemedia-typefilehosttagpathparenttagstag-datecollectiontie-typealltitleartistalbumyeartracktiedir-hashdir-uidversion-ofversion-date"

var _TieProperty_index = [...]uint8{0, 7, 15, 23, 27, 37, 45, 48, 52, 58, 62, 70, 80, 88, 91, 96, 102, 107, 111, 116, 127, 134, 144, 156}

func (i TieProperty) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TieProperty_index)-1 {
		return "TieProperty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TieProperty_name[_TieProperty_index[idx]:_TieProperty_index[idx+1]]
}
