// Code generated by "stringer -type=TieProperty -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TieUid-0]
	_ = x[TieDirectory-1]
	_ = x[TieFilename-2]
	_ = x[TieName-3]
	_ = x[TieMediaType-4]
	_ = x[TieFileHost-5]
	_ = x[TieTag-6]
	_ = x[TieTags-7]
	_ = x[TieTagDate-8]
	_ = x[TieGalleryName-9]
	_ = x[TieTypeProperty-10]
	_ = x[TieFiles-11]
	_ = x[TieDirectories-12]
	_ = x[TieCategory-13]
	_ = x[TieGalleries-14]
	_ = x[TieAll-15]
}

const _TieProperty_name = "tie-uiddirectoryfilenamenamemedia-typefilehosttagtagstag-dategallery-nametie-typetie-filestie-directoriestie-categorytie-galleriesall"

var _TieProperty_index = [...]uint8{0, 7, 16, 24, 28, 38, 46, 49, 53, 61, 73, 81, 90, 105, 117, 130, 133}

func (i TieProperty) String() string {
	if i < 0 || i >= TieProperty(len(_TieProperty_index)-1) {
		return "TieProperty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TieProperty_name[_TieProperty_index[i]:_TieProperty_index[i+1]]
}
