// Code generated by "stringer -type=TieType -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TieImageFile-0]
	_ = x[TieAudioFile-1]
	_ = x[TieVideoFile-2]
	_ = x[TieDocumentFile-3]
	_ = x[TieImageDir-4]
	_ = x[TieVideoDir-5]
	_ = x[TieDocumentDir-6]
	_ = x[TieImageArchive-7]
	_ = x[TieVideoArchive-8]
	_ = x[TieDocumentArchive-9]
}

const _TieType_name = "image-fileaudio-filevideo-filedocument-fileimage-dirvideo-dirdocument-dirimage-archivevideo-archivedocument-archive"

var _TieType_index = [...]uint8{0, 10, 20, 30, 43, 52, 61, 73, 86, 99, 115}

func (i TieType) String() string {
	if i < 0 || i >= TieType(len(_TieType_index)-1) {
		return "TieType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TieType_name[_TieType_index[i]:_TieType_index[i+1]]
}
