// Code generated by "stringer -type=TieType -linecomment"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TieUnknownFile-0]
	_ = x[TieImageFile-1]
	_ = x[TieAudioFile-2]
	_ = x[TieVideoFile-3]
	_ = x[TieDocumentFile-4]
	_ = x[TieArchiveFile-5]
	_ = x[TieImageDir-6]
	_ = x[TieAudioDir-7]
	_ = x[TieVideoDir-8]
	_ = x[TieDocumentDir-9]
	_ = x[TieImageArchive-10]
	_ = x[TieAudioArchive-11]
	_ = x[TieVideoArchive-12]
	_ = x[TieDocumentArchive-13]
	_ = x[TieDirectory-14]
	_ = x[TieFile-15]
}

const _TieType_name = "unknown-fileimage-fileaudio-filevideo-filedocument-filearchive-fileimage-diraudio-dirvideo-dirdocument-dirimage-archiveaudio-archivevideo-archivedocument-archivedirectoryfile"

var _TieType_index = [...]uint8{0, 12, 22, 32, 42, 55, 67, 76, 85, 94, 106, 119, 132, 145, 161, 170, 174}

func (i TieType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TieType_index)-1 {
		return "TieType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TieType_name[_TieType_index[idx]:_TieType_index[idx+1]]
}
