Username = 'defaultuser'
Password = 'defaultpassword'
Namespace = 'Examples'
Collection = 'add-get'
DaemonURL = 'http://localhost:1161'
DefaultFileHosts = ['default']

[FileHosts.default]
URL = 'http://localhost:1162'
