// Copyright 2015, David Howden
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
//
// Regression tests for the tie fork's audio-duration extraction. The per-format
// parsers read bit-packed header fields at fixed offsets (MP3 Xing/CBR, FLAC
// STREAMINFO, Ogg granule, MP4 mvhd); a stray offset silently yields a wildly
// wrong duration, so each fixture carries a distinct known length and the
// assertions are tight enough that a misparse fails rather than passing by luck.

package tag

import (
	"math"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// durationFixtures are generated by testdata/gen.sh (ffmpeg). Each has a
// deliberately distinct length so a parser returning another file's value, a
// hardcoded constant, or a zero cannot pass.
var durationFixtures = []struct {
	file    string
	format  Format
	kind    FileType
	wantSec float64
	tolSec  float64
}{
	// LAME writes an Info/Xing frame-count header; the reported time includes
	// encoder padding, hence the slightly-over-2s target and a looser tolerance.
	{"dur.mp3", ID3v2_4, MP3, 2.037, 0.15},
	{"dur.flac", VORBIS, FLAC, 3.000, 0.02},
	// Opus is clocked at 48 kHz with a pre-skip subtracted from the final granule.
	{"dur.opus", VORBIS, OGG, 4.006, 0.05},
	{"dur.ogg", VORBIS, OGG, 5.000, 0.02},
	// FileType stays Unknown: it is derived from an iTunes media-type ("stik")
	// atom, which ffmpeg's plain AAC/m4a output does not carry.
	{"dur.m4a", MP4, UnknownFileType, 6.000, 0.02},
}

func TestDurationFromFixtures(t *testing.T) {
	for _, tc := range durationFixtures {
		t.Run(tc.file, func(t *testing.T) {
			f, err := os.Open(filepath.Join("testdata", tc.file))
			if err != nil {
				t.Fatalf("open fixture: %v", err)
			}
			defer f.Close()

			m, err := ReadFrom(f)
			if err != nil {
				t.Fatalf("ReadFrom: %v", err)
			}
			if m.Format() != tc.format {
				t.Errorf("Format() = %q, want %q", m.Format(), tc.format)
			}
			if m.FileType() != tc.kind {
				t.Errorf("FileType() = %q, want %q", m.FileType(), tc.kind)
			}

			got := m.Duration().Seconds()
			if got == 0 {
				t.Fatalf("Duration() = 0; parser failed to derive a length")
			}
			if math.Abs(got-tc.wantSec) > tc.tolSec {
				t.Errorf("Duration() = %.3fs, want %.3f±%.3fs", got, tc.wantSec, tc.tolSec)
			}
		})
	}
}

func TestParseMP3FrameHeader(t *testing.T) {
	// MPEG1 Layer III, 128 kbit/s, 44.1 kHz, stereo:
	//   b1 = 1111 1011 -> sync + version=3 (MPEG1) + layer=1 (III) + protection
	//   b2 = 1001 0000 -> bitrate idx 9 (128k) + sr idx 0 (44100)
	//   b3 = 0000 0000 -> stereo (channelMode 0)
	valid := []byte{0xFF, 0xFB, 0x90, 0x00}
	h, ok := parseMP3FrameHeader(valid)
	if !ok {
		t.Fatalf("parseMP3FrameHeader(valid) ok=false")
	}
	if h.version != 3 || h.layer != 1 {
		t.Errorf("version/layer = %d/%d, want 3/1", h.version, h.layer)
	}
	if h.bitrate != 128000 {
		t.Errorf("bitrate = %d, want 128000", h.bitrate)
	}
	if h.sampleRate != 44100 {
		t.Errorf("sampleRate = %d, want 44100", h.sampleRate)
	}
	if h.samplesPerFrame != 1152 {
		t.Errorf("samplesPerFrame = %d, want 1152 (MPEG1 Layer III)", h.samplesPerFrame)
	}

	bad := [][]byte{
		{0x00, 0x00, 0x00, 0x00},       // no sync word
		{0xFF, 0xE0, 0x90, 0x00},       // sync but version bits = 1 (reserved)
		{0xFF, 0xF9, 0x90, 0x00},       // layer bits = 0 (reserved)
		{0xFF, 0xFB, 0x00, 0x00},       // bitrate index 0 (free)
		{0xFF, 0xFB, 0xF0, 0x00},       // bitrate index 15 (bad)
		{0xFF, 0xFB, 0x9C, 0x00},       // sample-rate index 3 (reserved)
		{0xFF, 0xFB},                    // too short
	}
	for i, b := range bad {
		if _, ok := parseMP3FrameHeader(b); ok {
			t.Errorf("parseMP3FrameHeader(bad[%d]) ok=true, want false", i)
		}
	}
}

func TestFramesToDuration(t *testing.T) {
	// 100 frames * 1152 samples / 48000 Hz = 2.4s.
	fh := mp3FrameHeader{sampleRate: 48000, samplesPerFrame: 1152}
	if got := framesToDuration(100, fh); got != 2400*time.Millisecond {
		t.Errorf("framesToDuration = %v, want 2.4s", got)
	}
	if got := framesToDuration(0, fh); got != 0 {
		t.Errorf("framesToDuration(0 frames) = %v, want 0", got)
	}
	if got := framesToDuration(100, mp3FrameHeader{samplesPerFrame: 1152}); got != 0 {
		t.Errorf("framesToDuration(sampleRate 0) = %v, want 0", got)
	}
}
